### ISSUE TITLE
Azure disks are not properly getting cleaned up by regardless of retention policy set to delete

### ISSUE THREAD

**Issue by heshanperera-alert** [kubernetes-sigs/azuredisk-csi-driver#1750] opened 2023-03-06 00:11 UTC
**What happened**: Azure disks are not properly getting cleaned up by the csi-driver though the retention policy is set to delete

**What you expected to happen**: Azure CSI should properly handle the delete pvc command where it should wait until it clears all the resources and should not conflict with the delete pv. With AWS this has never happened, and it's the standard way to clear up the resources on all the cloud platforms.

**How to reproduce it**: When you try to use the delete pv command and delete pvc commands consecutively to clean up this will show up.

**Anything else we need to know?**:

**Environment**:

- CSI Driver version: azuredisk-csi:v1.26.2
- Kubernetes version (use `kubectl version`): 1.24.6

**Comment by andyzhangx** [comment] 2023-03-06 03:34
@heshanperera-alert is it on AKS? if yes, what's the pv uuid? And as I know, if PV is created automatically (dynamic provisioning), you only need to delete pvc, and then pv is deleted automatically.

**Comment by heshanperera-alert** [comment] 2023-03-07 05:28
Yes its on AKS. Is there a documentation that specifically shows that this is the intended behavior. As far as we experienced, all the other cloud providers did not had any issues when used delete pvc and delete pv consecutively.

**Comment by andyzhangx** [comment] 2023-03-07 07:21
> Yes its on AKS. Is there a documentation that specifically shows that this is the intended behavior. As far as we experienced, all the other cloud providers did not had any issues when used delete pvc and delete pv consecutively.

@heshanperera-alert what's the error you got? could you paste the error details?

**Comment by heshanperera-alert** [comment] 2023-03-07 15:13
@andyzhangx we did not receive any error. We did not even notice that its leaking drives until we got a huge bill. Then only we started testing and realized that the disks are always leaking when we execute `kubectl delete pvc` and then `kubectl delete pv`

We did not had this issue with the other cloud providers.

**Comment by andyzhangx** [comment] 2023-03-08 08:31
> @andyzhangx we did not receive any error. We did not even notice that its leaking drives until we got a huge bill. Then only we started testing and realized that the disks are always leaking when we execute `kubectl delete pvc` and then `kubectl delete pv`
> 
> We did not had this issue with the other cloud providers.

@heshanperera-alert I have execute `kubectl delete pvc` and then `kubectl delete pv`, and if the pod with that volume is still in Running, when it's detached, kube-controller-manager won't even call `DeleteVolume` in CSI driver. Not sure it's by design or not, but the correct behavior is only execute `kubectl delete pvc`, and the corresponding pv would be deleted automatically, so you don't even execute `kubectl delete pv`

**Comment by andyzhangx** [comment] 2023-03-12 06:54
> @andyzhangx Thanks for the continuous response with this. But we have worked with other cloud providers this same way and did not had any issues like this with them. As you said, how do we confirm whether this is the correct behavior. If its the correct one, where could we find a documentation for that?

@heshanperera-alert per below CSI spec, csi-provisioner sidecar container would delete `PersistentVolume` object, so it's not necessary to delete pv by end user:

https://github.com/kubernetes/design-proposals-archive/blob/main/storage/container-storage-interface.md#master-to-csi-driver-communication

To delete a CSI volume, an end user would delete the corresponding `PersistentVolumeClaim` object. The external provisioner will react to the deletion of the PVC and based on its reclamation policy it will issue the `DeleteVolume` call against the CSI volume driver commands to delete the volume. It will then delete the `PersistentVolume` object.

**Comment by bene-tleilax-werdna** [comment] 2023-03-15 18:28
Can confirm the same behavior reported by @heshanperera-alert with CSI version 1.26.2 and AKS k8s version 1.25.5.

In addition, I have noticed persistent volumes stuck on Terminating status and have had to set the `finalizers` annotation on the PV resource to null to remove the k8s resource. After this, I have to manually delete the disks in Azure.

Unfortunately, I have had to get into the habit of manually checking the disks in Azure to avoid getting hit with charges for unused disks.

**Comment by andyzhangx** [comment] 2023-03-16 03:39
> Can confirm the same behavior reported by @heshanperera-alert with CSI version 1.26.2 and AKS k8s version 1.25.5.
> 
> In addition, I have noticed persistent volumes stuck on Terminating status and have had to set the `finalizers` annotation on the PV resource to null to remove the k8s resource. After this, I have to manually delete the disks in Azure.
> 
> Unfortunately, I have had to get into the habit of manually checking the disks in Azure to avoid getting hit with charges for unused disks.

@bene-tleilax-werdna per this commet(https://github.com/kubernetes-sigs/azuredisk-csi-driver/issues/1750#issuecomment-1465106866), pls do not remove persistent volume manually, you only need to remove PVC, and pv will be removed by external provisioner sidecar container in CSI driver automatically if retentionPolicy is set as delete

**Comment by bene-tleilax-werdna** [comment] 2023-03-16 12:26
Please note the reason we had to remove persistent volumes manually is because they were not removed after the PVC was deleted. I understand you should only delete the PVC and the PV should be removed automatically if the retentionPolicy is set to Delete, however, experience using AKS has proven that often times it fails to delete the PV and its disk after the PVC is removed. Failing to check these and remove them manually has resulted in getting charged a bill for a resource we thought the platform would remove automatically. Just because the platform should behave in a certain way doesn't mean it is behaving in that way.

**Comment by heshanperera-alert** [comment] 2023-03-16 13:28
> To delete a CSI volume, an end user would delete the corresponding `PersistentVolumeClaim` object. The external provisioner will react to the deletion of the PVC and based on its reclamation policy it will issue the `DeleteVolume` call against the CSI volume driver commands to delete the volume. It will then delete the `PersistentVolume` object.

@andyzhangx According to the documentation it says that it will delete the pv depending on the reclamation policy once you delete the PVC.. But it doesn't say the fact that you should not delete the PV because it will leak volumes in azure. As I pointed out number of times, why this behavior happens only with AKS, its obvious that there is a bug with CSi driver where it doesn't properly handle the deletion

**Comment by andyzhangx** [comment] 2023-03-16 14:07
> > To delete a CSI volume, an end user would delete the corresponding `PersistentVolumeClaim` object. The external provisioner will react to the deletion of the PVC and based on its reclamation policy it will issue the `DeleteVolume` call against the CSI volume driver commands to delete the volume. It will then delete the `PersistentVolume` object.
> 
> @andyzhangx According to the documentation it says that it will delete the pv depending on the reclamation policy once you delete the PVC.. But it doesn't say the fact that you should not delete the PV because it will leak volumes in azure. As I pointed out number of times, why this behavior happens only with AKS, its obvious that there is a bug with CSi driver where it doesn't properly handle the deletion

@heshanperera-alert though it's not mentioned in the doc, but from below external-provisioner code, it's calling CSI driver `DeleteVolume` func first, and then external-provisioner container would delete PV itself

https://github.com/kubernetes-csi/external-provisioner/blob/cd81ed5d31835d1aabad74db869c1165df9e3666/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v8/controller/controller.go#L1473-L1490

If you delete PVC and PV manually together, there is a race condition that csi-provisioner and k8s pv controller would both delete the pv in same time.

@bene-tleilax-werdna the issue you hit should be different issue, if you have a disk pv name at hand, I could help you analyze why pvc is deleted and disk pv is still stuck there, I could get some csi driver logs which indicates the disk deletion error.

**Comment by heshanperera-alert** [comment] 2023-03-16 15:39
@bene-tleilax-werdna I noticed that your case is also there but could not confirm because there are more than 100 people creating clusters per a day, and some of them use different tools to create cluster. I cant yet confirm this issue as I couldn't replicate.

But its sure that it happens when people issued the delete PVC and delete PV command one after the other. I have replicated it number of times.

@andyzhangx  isnt the CSI driver suppose to handle it the way other cloud providers handle it so that it wont have an effect with the race condition?

**Comment by andyzhangx** [comment] 2023-04-15 14:41
FYI. We have added doc about disk volume deletion:
https://learn.microsoft.com/en-us/azure/aks/csi-storage-drivers
```
It is recommended to delete the corresponding PersistentVolumeClaim object instead of the PersistentVolume object when deleting a CSI volume. The external provisioner in the CSI driver will react to the deletion of the PersistentVolumeClaim and based on its reclamation policy, it will issue the DeleteVolume call against the CSI volume driver commands to delete the volume. The PersistentVolume object will then be deleted.
```

if you delete PersistentVolume object explicitly, there is only one CSI driver call to delete the disk volume in the backend, and if disk is still attached to the node (in detaching state), that disk volume deletion would fail, and then disk volume won't be deleted any more. And if you only delete PVC object explicitly, the external-provisioner and CSI driver would try to delete the disk volume infinitely until it's detached from the node and deleted.

There is issue in the before that azure disk detach is slower, that could lead to this issue. And from 2023 March, AKS has enabled `Peregrine` which makes disk attach/detach faster now for **new** node pool. While we still recommend only delete the pvc ojbect explicitly to avoid such race condition.

I will close this issue, let me know if you have any other questions, thanks.

**Closed by andyzhangx** 2023-04-15 14:41 UTC
Labels: kind/support

**Comment by mdnix** [comment] 2023-07-05 07:43
We've been seeing the same thing happening over and over again. We don't delete the PV. Instead, we clean up the PVC and let the external system handle the rest. We thought this would cover everything, but we found out yesterday that's not the case. There are a lot of disks that aren't attached to anything. What's worse is that this is happening on many clusters we're running, and we didn't realize it until now.

**Comment by mdnix** [comment] 2023-09-04 07:59
@andyzhangx We are still experiencing this issue. Although we are not directly deleting the PV, some of our users occasionally delete the Namespace. However, this should trigger the deletion of the PVC, which would ultimately lead to the disk being deleted. Is there any known issue?

**Comment by heshanperera-alert** [comment] 2023-09-05 00:53
Same for us, we still see the issue.

**Comment by andyzhangx** [comment] 2023-09-05 11:19
this is related to https://kubernetes.io/blog/2021/12/15/kubernetes-1-23-prevent-persistentvolume-leaks-when-deleting-out-of-order/, while `HonorPVReclaimPolicy` is still in alpha stage now

**Comment by mdnix** [comment] 2023-09-05 13:10
@andyzhangx Thank you for the update! Am I correct in assuming that the feature gate is not yet enabled in AKS? How can I check which feature gates are currently enabled? We are running a mix of clusters with versions 1.25.x and 1.26.x.

**Comment by andyzhangx** [comment] 2023-09-05 13:24
> @andyzhangx Thank you for the update! Am I correct in assuming that the feature gate is not yet enabled in AKS? How can I check which feature gates are currently enabled? We are running a mix of clusters with versions 1.25.x and 1.26.x.

@mdnix since this is an alpha feature, I think we could enable this feature on AKS 1.28 which is going to preview next month. Enable this alpha feature on existing AKS version would be at risk.
