### ISSUE TITLE
Volumes on Azure Stack Hub do not have correct topology

### ISSUE THREAD

**Issue by jsafrane** [kubernetes-sigs/azuredisk-csi-driver#1013] opened 2021-09-09 13:41 UTC
**What happened**:
Running v1.5.1 on Azure Stack Hub, I noticed that PVs have a wrong affinity and nodes have wrong labels.

 PV:
```
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.disk.csi.azure.com/zone
            operator: In
            values:
            - ""
```

Node:
```
      topology.disk.csi.azure.com/zone: ""
      topology.kubernetes.io/region: ppe3
      topology.kubernetes.io/zone: "1"
```

So, the external cloud controller knows correct location (ppe3/1), but the CSI driver does not.

**What you expected to happen**:
Both PVs and Nodes would have some topology, either `topology.disk.csi.azure.com/zone: 1` or `ppe3-1`

**How to reproduce it**:
Run the CSI driver in AzureStackHub with cloud config with `"useInstanceMetadata":false`.

**Anything else we need to know?**:
Looking at the code in [NodeGetInfo](https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/4c052cc47c2d67d8bbffbb31f13bbf33ca4d0630/pkg/azuredisk/nodeserver.go#L321), I can see

* `zone`, as returned by `d.cloud.GetZone(ctx)`,  is `{FailureDomain:1 Region:ppe3}`
* `d.cloud.Location` is `ppe3`
* `isAvailabilityZone` checks that `FailureDomain` has prefix `ppe3`, which it does not and therefore the driver reports `{"accessible_topology":{"segments":{"topology.disk.csi.azure.com/zone":""}}`

**Environment**:
- CSI Driver version: 1.5.1
- Kubernetes version (use `kubectl version`): v1.22.0-rc.0
- OS (e.g. from /etc/os-release): RHEL 8.4
- Kernel (e.g. `uname -a`):  4.18.0-305.12.1.el8_4.x86_64
- Install tools: OpenShift

**Comment by jsafrane** [comment] 2021-09-09 13:44
I am not very familiar in this area, to me it looks like `GetZone()` should return `FailureDomain: ppe3-1, Region:ppe3`. To make that happen, `GetZoneByNodeName` should use `as.makeZone()` instead of a plain number [here](https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/4c052cc47c2d67d8bbffbb31f13bbf33ca4d0630/vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_standard.go#L607).

Did anyone test running the driver with `"useInstanceMetadata":false`?

**Comment by jsafrane** [comment] 2021-09-09 13:49
BTW, this will be super hard to fix in a running cluster, because we can't change `PV.spec.nodeAffinity` once a PV was created. A cluster with the faulty PVs *must* always run a CSI driver that reports `topology.disk.csi.azure.com/zone: ""` to make sure these old PVs are working.

**Comment by andyzhangx** [comment] 2021-09-09 13:50
I am not familiar with zone on azure stack. @songjiaxun do you know whether Azure Stack supports zone? From the above info with public cloud zone rules, that cluster is located in region `ppe3`, and fault domain is `1`, that's not a zone node pool, it's in one availability set.

If one node is in zone # 1,  `GetZone` func should return `region-1`

**Comment by andyzhangx** [comment] 2021-09-09 13:51
Aha, I think that's not a zone cluster, it's a cluster within an availability set with fault domain num.

**Comment by andyzhangx** [comment] 2021-09-09 13:52
but anyway, does volume scheduling works on such cluster on Azure stack?

**Comment by jsafrane** [comment] 2021-09-09 14:05
I my Azure stack hub, I can see all `disks` and `virtualMachines` do **not** have any `zone` / `zones`  fields  in their jsons (I see them in the real Azure cloud). I can see the VMs in ASH have a fault domain assigned, some nodes have "0", some have "1". Not sure if it represents something like "Zone". It seems that the disks can be used by any VM in both failure domains, at least in my env.

So, `topology.disk.csi.azure.com/zone":""` could be actually correct, if ASH guarantees all VMs can always access all Disks. Still, it works just by accident. Proper code path would be better.

**Comment by jsafrane** [comment] 2021-09-09 16:12
Maybe my problem is related to using fault domains and not really ASH. Is can a disk be atttached to all VMs in all fault domains? If so, why the driver uses it for topology restriction?

**Comment by songjiaxun** [comment] 2021-09-09 19:13
@jsafrane Thanks for reporting this issue. I don't think Azure Stack Hub supports zones, which means the zones or topology related features were not tested on Azure Azure Hub. That being said, we are running e2e tests thoroughly on Azure Stack Hub to make sure other features work. To me, it seems like it just works by accident. However, the behaviour is what we expect -- empty value for `topology.disk.csi.azure.com/zone` on Azure Stack Hub. As for why `topology.kubernetes.io` labels are put on nodes, I am not 100% sure, but it should not affect the usage of the CSI driver.

My question would be the same: can the PV and Pods be scheduled to nodes correctly? If so, and if the value of `topology.disk.csi.azure.com/zone` will always be empty on Azure Stack Hub, then I believe we are good. @andyzhangx Please correct me if I am wrong.

**Comment by songjiaxun** [comment] 2021-09-09 19:39
Created a new different issue for the newer CSI version, the fix for this issue may solve the problem here as well. https://github.com/kubernetes-sigs/azuredisk-csi-driver/issues/1014

**Comment by andyzhangx** [comment] 2021-09-10 01:50
if current node pool does not support zone, `topology.disk.csi.azure.com/zone: ""` is the correct setting, which could make sure PV could be scheduled to any node. We only set non-empty value for zone node, so this is expected and by design. It's not working **by accident**, it's working by our design.

**Comment by jsafrane** [comment] 2021-09-10 08:51
> if current node pool does not support zone, `topology.disk.csi.azure.com/zone: ""` is the correct setting

I agree.

> It's not working by accident, it's working by our design.

I don't agree here. It works only because `d.cloud.GetZone(ctx)` goes through `availabilitySet` path, which returns `FailureDomain:1` and not `FailureDomain:ppe3-1`.  This is not very obvious. I'd expect that `GetZone` sees that this particular Azure does not support zones and returns something that makes it obvious. Why is failure domain index returned here instead of `""`?
https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/4c052cc47c2d67d8bbffbb31f13bbf33ca4d0630/vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_standard.go#L607

**Comment by andyzhangx** [comment] 2021-09-10 08:58
about `GetZone` value, doc is here:
https://kubernetes-sigs.github.io/cloud-provider-azure/topics/availability-zones/#node-labels
```
Both zoned and unzoned nodes are supported, but the value of node label failure-domain.beta.kubernetes.io/zone are different:

For zoned nodes, the value is <region>-<AZ>, e.g. centralus-1.
For unzoned nodes, the value is faultDomain, e.g. 0.
```

**Comment by jsafrane** [comment] 2021-09-10 09:45
Thanks for the link, that explains it's really a design. Sorry about the noise. A comment somewhere in the code would help :-).

**Comment by andyzhangx** [comment] 2021-09-10 09:48
sure, I will leave a comment in the code, just keep this issue open, will work out a PR to close this issue, thanks.

**Closed** 2021-09-21 01:36 UTC
